version: '3'

services:
  app:
    image: rojima1/android-studio
    privileged: true
    command: /opt/android-studio/bin/studio.sh
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
